import type { Uh } from "./types";
import type { Caracteristica } from "../caracteristica/types";

export const blankUh = (): Uh => ({
  id: 0,
  iduh: 0,
  idempresa: 0,
  empresa_dsabreviatura: "",
  cduh: "",
  iduhtipo_emp: 0,
  idedificacao: 0,
  idandar: 0,
  dsuh: "",
  qtquarto: 0,
  flestoque: 0,
  ispaxadicional: 0,
  iduhclassificacao: 0,
  isativo: 0,
  isconjugada: 0,
  isacessibilidade: 0,
  iduhtipo: 0,
  nmuhtipo: "",
  nmuhtipo_emp_flsituacao: 0,
  nmandar: "",
  andar_isativo: 0,
  nmedificacao: "",
  dsidentificador: "",
  uhclassificacao_isativo: 0,
  conjugadas: [],
  caracteristicas: [] as Caracteristica[],
  pessoaanotacao: [],
});
