import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('hospedes').del();

  await knex('hospedes').insert([
    {
      idhospede: 1, idempresa: 1,
      nmhospede: 'Carlos Eduardo Silva',
      cpf_cnpj: '123.456.789-00',
      email: 'carlos.silva@email.com',
      telefone: '(11) 98765-4321',
      dtnascimento: '1985-03-15',
      dsnacionalidade: 'Brasileira',
      dsobservacao: null,
      isativo: 1,
    },
    {
      idhospede: 2, idempresa: 1,
      nmhospede: 'Ana Beatriz Costa',
      cpf_cnpj: '987.654.321-00',
      email: 'ana.costa@email.com',
      telefone: '(21) 91234-5678',
      dtnascimento: '1990-07-22',
      dsnacionalidade: 'Brasileira',
      dsobservacao: 'Alergica a frutos do mar',
      isativo: 1,
    },
    {
      idhospede: 3, idempresa: 1,
      nmhospede: 'John Smith',
      cpf_cnpj: 'US-A12345678',
      email: 'john.smith@email.com',
      telefone: '+1 (555) 123-4567',
      dtnascimento: '1978-11-30',
      dsnacionalidade: 'Americana',
      dsobservacao: 'Fala apenas inglês',
      isativo: 1,
    },
    {
      idhospede: 4, idempresa: 1,
      nmhospede: 'Mariana Oliveira Santos',
      cpf_cnpj: '456.789.012-34',
      email: 'mariana.santos@email.com',
      telefone: '(31) 97654-3210',
      dtnascimento: '1995-01-08',
      dsnacionalidade: 'Brasileira',
      dsobservacao: null,
      isativo: 1,
    },
    {
      idhospede: 5, idempresa: 1,
      nmhospede: 'Roberto Ferreira Lima',
      cpf_cnpj: '321.654.987-00',
      email: 'roberto.lima@email.com',
      telefone: '(41) 96543-2109',
      dtnascimento: '1972-09-14',
      dsnacionalidade: 'Brasileira',
      dsobservacao: 'Precisa de quarto no térreo (dificuldade de locomoção)',
      isativo: 1,
    },
    {
      idhospede: 6, idempresa: 2,
      nmhospede: 'Fernanda Alves Pereira',
      cpf_cnpj: '654.321.098-76',
      email: 'fernanda.pereira@email.com',
      telefone: '(51) 95432-1098',
      dtnascimento: '1988-05-25',
      dsnacionalidade: 'Brasileira',
      dsobservacao: null,
      isativo: 1,
    },
    {
      idhospede: 7, idempresa: 2,
      nmhospede: 'Lucas Mendes Rocha',
      cpf_cnpj: '789.012.345-67',
      email: 'lucas.rocha@email.com',
      telefone: '(61) 94321-0987',
      dtnascimento: '1993-12-03',
      dsnacionalidade: 'Brasileira',
      dsobservacao: null,
      isativo: 1,
    },
    {
      idhospede: 8, idempresa: 3,
      nmhospede: 'Sophie Dubois',
      cpf_cnpj: 'FR-P123456',
      email: 'sophie.dubois@email.fr',
      telefone: '+33 6 12 34 56 78',
      dtnascimento: '1982-04-17',
      dsnacionalidade: 'Francesa',
      dsobservacao: 'Vegetariana',
      isativo: 1,
    },
    {
      idhospede: 9, idempresa: 3,
      nmhospede: 'Pedro Henrique Carvalho',
      cpf_cnpj: '147.258.369-00',
      email: 'pedro.carvalho@email.com',
      telefone: '(71) 93210-9876',
      dtnascimento: '1980-08-20',
      dsnacionalidade: 'Brasileira',
      dsobservacao: null,
      isativo: 1,
    },
    {
      idhospede: 10, idempresa: 1,
      nmhospede: 'Juliana Nunes Barbosa',
      cpf_cnpj: '258.369.147-00',
      email: 'juliana.barbosa@email.com',
      telefone: '(81) 92109-8765',
      dtnascimento: '1997-06-11',
      dsnacionalidade: 'Brasileira',
      dsobservacao: null,
      isativo: 1,
    },
  ]);
}
